trigger:
- master
- develop

resources:
- repo: self

variables:
  imageName: 'projectorigin/identity-service'
  vmImageName: 'ubuntu-latest'
  ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
    tag: '$(Build.BuildId)'
    namespace: 'project-origin'
  ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
    tag: 'dev.$(Build.BuildId)'
    namespace: 'dev-project-origin'

stages:
- stage: build_and_publish
  displayName: Build and publish
  jobs:  
  - job: docker_build_push
    displayName: Docker build and push
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build docker image
      inputs:
        command: build
        repository: $(imageName)
        Dockerfile: Dockerfile
        tags: |
          latest
          $(tag)
    - task: Docker@2
      displayName: Push image
      inputs:
        command: push
        repository: $(imageName)
        containerRegistry: dockerHub
        tags: |
          latest
          $(tag)

          
- stage: update_cluster
  displayName: Update kubernetes
  jobs:  
  - job: push_to_cluster
    displayName: Push to Cluster
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: HelmDeploy@0
        displayName: Helm upgrade
        inputs:
          connectionType: 'Kubernetes Service Connection'
          kubernetesServiceConnection: 'origin-kubernetes-connection'
          namespace: $(namespace)
          command: upgrade
          chartType: filepath
          chartPath: ./chart
          releaseName: identity-service
          overrideValues: tag=$(tag)
          install: true
          waitForExecution: true