"""empty message

Revision ID: 81599bf9524e
Revises: ab58866cefbc
Create Date: 2020-05-18 10:11:22.444280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81599bf9524e'
down_revision = 'ab58866cefbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('activate_token', sa.String(), nullable=True))
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    op.execute("UPDATE \"user\" SET active = 't'")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'active')
    op.drop_column('user', 'activate_token')
    # ### end Alembic commands ###
