"""empty message

Revision ID: 9f72b7fe7d41
Revises: f50c2b04f299
Create Date: 2020-05-09 13:16:50.827896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f72b7fe7d41'
down_revision = 'f50c2b04f299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('reset_password_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'reset_password_token')
    # ### end Alembic commands ###
