"""empty message

Revision ID: cbc4fdb8b23a
Revises: 81599bf9524e
Create Date: 2020-05-18 19:40:56.595370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbc4fdb8b23a'
down_revision = '81599bf9524e'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE \"user\" SET active = 't'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
